# ── Stage 1: Install dependencies ────────────────────────────────────
# Separate dependency install from build for better layer caching.
FROM node:20-alpine AS deps
WORKDIR /app

RUN apk add --no-cache \
    openssl~3 \
    libc6-compat~1

ENV NPM_CONFIG_LOGLEVEL=warn \
    NPM_CONFIG_REGISTRY=https://registry.npmjs.org \
    NEXT_TELEMETRY_DISABLED=1

# Copy only package manifests first for maximum layer cache reuse.
COPY package.json package-lock.json lockfile-check.js ./
COPY prisma ./prisma
COPY scripts ./scripts
COPY lib ./lib

RUN node ./lockfile-check.js
RUN npm ci --no-audit --no-fund

# ── Stage 2: Build application ───────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app

RUN apk add --no-cache \
    openssl~3 \
    libc6-compat~1

ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Preserve Prisma CLI + engines for runtime migrations before pruning
RUN mkdir -p /opt/runtime-prisma && \
    cp -R node_modules/prisma /opt/runtime-prisma/prisma && \
    cp -R node_modules/@prisma /opt/runtime-prisma/@prisma

RUN npm run build
RUN npm prune --production

# ── Stage 3: Production runner ───────────────────────────────────────
# Minimal runtime with only the artifacts needed to run the application.
# The standalone output includes its own node_modules subset, so we only
# add back Prisma (for runtime migrations) and other runtime-only deps.
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1

RUN apk add --no-cache \
    openssl~3 \
    libc6-compat~1 \
    wget~1 \
    su-exec~0.3 \
    tini~0.19

# Non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# 1. Public assets
COPY --from=builder /app/public              ./public

# 2. Next.js standalone output (includes server.js and its own node_modules)
COPY --from=builder /app/.next/standalone    ./

# 3. Static assets generated by Next.js
COPY --from=builder /app/.next/static        ./.next/static

# 4. Prisma schema + migrations (needed for migrate deploy at startup)
COPY --from=builder /app/prisma              ./prisma

# 5. Selective production dependencies:
#    - Restore Prisma CLI/engines from pre-prune backup (for runtime migrations).
#    - Copy only specific runtime packages not bundled by Next.js standalone.
#    The standalone output already includes most required node_modules.
COPY --from=builder /opt/runtime-prisma/prisma  ./node_modules/prisma
COPY --from=builder /opt/runtime-prisma/@prisma ./node_modules/@prisma
# Runtime deps that standalone may not bundle (Socket.IO, tsx, redis, argon2, etc.)
COPY --from=builder /app/node_modules/socket.io       ./node_modules/socket.io
COPY --from=builder /app/node_modules/socket.io-adapter ./node_modules/socket.io-adapter
COPY --from=builder /app/node_modules/engine.io       ./node_modules/engine.io
COPY --from=builder /app/node_modules/tsx              ./node_modules/tsx
COPY --from=builder /app/node_modules/argon2           ./node_modules/argon2
COPY --from=builder /app/node_modules/web-push         ./node_modules/web-push
COPY --from=builder /app/node_modules/redis            ./node_modules/redis
COPY --from=builder /app/node_modules/otpauth          ./node_modules/otpauth
COPY --from=builder /app/node_modules/@socket.io       ./node_modules/@socket.io

# 6. Server source and related scripts
COPY --from=builder /app/server.ts           ./
COPY --from=builder /app/next.config.ts      ./
COPY --from=builder /app/tsconfig.json       ./
COPY --from=builder /app/instrumentation.ts  ./
COPY --from=builder /app/lib                 ./lib
COPY --from=builder /app/package.json        ./

# Copy entrypoint script.
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Copy backup script for automated cron
COPY --from=builder /app/scripts/backup.ts   ./scripts/backup.ts

# Create required directories (writable by the non-root user)
RUN mkdir -p public/uploads && \
    mkdir -p /app/backups && \
    chown -R nextjs:nodejs /app

EXPOSE 3000
ENV PORT=3000 \
    HOSTNAME=0.0.0.0

# Use tini as PID 1 for proper signal handling (graceful shutdown)
ENTRYPOINT ["/sbin/tini", "--"]

# Health check
HEALTHCHECK --interval=15s --timeout=10s --start-period=180s --retries=12 \
  CMD wget -qO- http://127.0.0.1:3000/api/health/live || exit 1

CMD ["/docker-entrypoint.sh"]
